"""empty message

Revision ID: da4de0486278
Revises: cb431f9c1697
Create Date: 2019-05-23 15:50:22.963360

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da4de0486278'
down_revision = 'cb431f9c1697'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book', sa.Column('end_date', sa.Date(), nullable=True))
    op.add_column('book', sa.Column('start_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('book', 'start_date')
    op.drop_column('book', 'end_date')
    # ### end Alembic commands ###
